#Tresc skopiowana z https://github.com/anothrNick/github-tag-action/blob/master/README.md
name: Tag version
on:
  workflow_dispatch:  #Manual start
  push:               #Push
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      release_tag: ${{ steps.gen_tag.outputs.new_tag }}
    steps:
    - name: Step1 - Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: Step2 - Bump version and push tag
      id: gen_tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
